spring:
  application:
    name: Api-Gateway
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  profiles:
    active: dev

server:
  port: 8080

ribbon:
  ReadTimeout: 6000000
  connection-timeout: 30000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

zuul:
  ribbon:
    eager-load:
      enabled: true
  semaphore:
    max-semaphores: 500
  sensitive-headers:
    - Authorization,Cookie,Set-Cookie
  routes:
   obe-auth-service: /api/v1/auth/**
   serviceId: obe-auth-service
   sensitive-headers: Cookie,Set-Cookie,Authorization
   ignored-patterns: /**/private/**
